title: Christopher Grace
logo: "/Images/Chris-Professional-Web_sm.png?raw=true"
description: > 
  Data Analyst | Senior Mechanical Engineer
  <br><br>
  <a href="https://www.linkedin.com/in/cgrace2">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
# Google Analytics tracking ID here
